#pragma once

#include "NativeGameplayTags.h"

namespace YMRPGGameplayTags
{
	YMRPG_API	FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);

	YMRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);

	YMRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	YMRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	YMRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	YMRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	YMRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	YMRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AutoRun);

	YMRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Melee);
	YMRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AirAttack);
	YMRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Key_1);
	YMRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Key_2);
	YMRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Key_3);
	YMRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Key_4);


	YMRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	YMRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset);
	YMRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_RequestReset);

	YMRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	YMRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Heal);


	YMRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouching);
	YMRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_AutoRunning);
	YMRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	YMRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	YMRPG_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);
}